// try{
//     let x= undefined;
//     console.log(x[0]);
// } catch (err) {
//     console.log("error handling in catch",err);
// }finally{
//     console.log("finally always gets executed")
// }

try{
    console.log("asalamualaikum");
    // console.log(a);

}catch (err) {
console.log("handled", err)
}
console.log("end");


try{
    console.log("hello")
    console.log(x)
}catch{
console.log("In this code there is some error plz check code try again ")
}

console.log("end");